/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 rhetorician.glb 
Author: engine9 (https://sketchfab.com/engine9)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/rhetorician-a89f035291d843069d73988cc0e25399
Title: Rhetorician
*/


import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

import rhetoricianScene from '../assets/3d/rhetorician.glb';

const rhetorician = (props) => {
  const rhetoricianRef = useRef()
  const { nodes, materials, animations } = useGLTF(rhetoricianScene)
  const { actions } = useAnimations(animations, a.group)
  return (
    <a.group ref={rhetoricianRef} {...props} >
      <a.group name="Sketchfab_Scene">
        <a.group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <a.group name="Root">
            <a.group name="mentor_roman_retopo" position={[-0.266, 0.12, 1.326]}>
              <mesh name="mentor_roman_retopo_0" geometry={nodes.mentor_roman_retopo_0.geometry} material={materials.Stone} />
            </a.group>
            <a.group name="Empty" position={[0.161, -0.17, 4.808]} rotation={[-0.104, 0.099, 0.002]} scale={0.892}>
              <a.group name="nimbus002">
                <mesh name="nimbus002_0" geometry={nodes.nimbus002_0.geometry} material={materials.Crown} />
              </a.group>
              <a.group name="nimbus001">
                <mesh name="nimbus001_0" geometry={nodes.nimbus001_0.geometry} material={materials.Crown} />
              </a.group>
              <a.group name="nimbus003">
                <mesh name="nimbus003_0" geometry={nodes.nimbus003_0.geometry} material={materials.Crown} />
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </a.group>
  )
}

export default rhetorician;
